### PR TITLE
Add auto accept flag

### PR DESCRIPTION
**Pull request by eric-gonzales**
Add an `auto_accept` flag in case the connection should not automatically be accepted. Default to `true` for backwards compatibility. 

Also added a `.gitignore` file and fixed an error in the readme.

### CODE REVIEW

**Comment by thomasbiddle** [comment]
@eric-gonzales I don't have the opportunity to test this right now; the only concern I have is sometimes Terraform doesn't play nice with booleans and it wants things converted to a string.

Have you tested this? Everything else looks good 👌

**Comment by eric-gonzales** [comment]
@thomasbiddle, currently have this running on a project I'm working on - it works fine with the boolean or the string. I'm fine switching it if you prefer.

**Review by thomasbiddle — APPROVED** [review]
🚀

**Comment by thomasbiddle** [comment]
Great! Thanks for the contribution!

**Pull request merged**
